"""initial schema

Revision ID: ea6809c9dc19
Revises: 
Create Date: 2026-02-15 20:00:34.707075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ea6809c9dc19'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'object_key',
               existing_type=mysql.VARCHAR(length=512),
               comment='COS object key',
               existing_comment='MinIO object key',
               existing_nullable=False)
    op.alter_column('photos', 'aperture',
               existing_type=mysql.FLOAT(),
               comment='f-number, e.g. 2.8',
               existing_nullable=True)
    op.alter_column('photos', 'shutter_speed',
               existing_type=mysql.VARCHAR(length=50),
               comment='e.g. 1/250',
               existing_nullable=True)
    op.alter_column('photos', 'focal_length',
               existing_type=mysql.FLOAT(),
               comment='mm',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'focal_length',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='mm',
               existing_nullable=True)
    op.alter_column('photos', 'shutter_speed',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment='e.g. 1/250',
               existing_nullable=True)
    op.alter_column('photos', 'aperture',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='f-number, e.g. 2.8',
               existing_nullable=True)
    op.alter_column('photos', 'object_key',
               existing_type=mysql.VARCHAR(length=512),
               comment='MinIO object key',
               existing_comment='COS object key',
               existing_nullable=False)
    # ### end Alembic commands ###
